### ISSUE TITLE
Removes all messages

### ISSUE THREAD

**Issue by Fest41** [kristoffer-tvera/wow-addon-guildMessageRemover#1]
Addon removes everyone messages not only mine. It may be caused by the fact that I can moderate guild chat.

**Comment by kristoffer-tvera** [comment]
You are indeed correct. I will bang out a fix after work tomorrow

**Comment by kristoffer-tvera** [comment]
I've addressed this.

The latest version has this "functionality" disabled by default, and only deletes your own messages.
There is now a option to enable the deletion of everyones messages (granted you need permission to do so)
